### ISSUE TITLE
Installing Drupal Console with PHP 5.6

### ISSUE THREAD

**Issue by stevenspasbo** [hechoendrupal/DrupalConsole#1080]
I was having issues installing with PHP 5.6, but was pointed in the direction of [this](http://stackoverflow.com/questions/6146362/readfile-fails-because-of-ssl) stackoverflow answer.

In the installer (which I didn't see in the repo or I would have sent a PR), you need to set the SSL options `verify_peer` and `verify_peer_name`.

On line 145 I added

    $arrContextOptions=array(
        "ssl"=>array(
            "verify_peer"=>false,
            "verify_peer_name"=>false,
        ),
    );

Then in the two `file_get_contents` calls

    $manifest = file_get_contents('http://drupalconsole.com/manifest.json', false, stream_context_create($arrContextOptions));

and

    file_put_contents($item->name, file_get_contents($item->url, false, stream_context_create($arrContextOptions)));

**Comment by jmolivas** [comment]
@stevenspasbo: Thanks for the issue, this is a duplicated and already reported at https://github.com/hechoendrupal/DrupalConsole/issues/1063 and fixed with https://github.com/hechoendrupal/DrupalConsole/pull/1065 and then rewrote with https://github.com/hechoendrupal/DrupalConsole/pull/1077

This fix will be included on the next release.

**Comment by jmolivas** [comment]
Fixed and included on v0.9.5 https://github.com/hechoendrupal/DrupalConsole/releases/tag/0.9.5
