### ISSUE TITLE
[module:install] Can't install module if previous configuration still exists

### ISSUE THREAD

**Issue by GoZOo** [hechoendrupal/DrupalConsole#1232]
# Problem / Motivation

In case a module has not been uninstalled properly, the next time i want to install it, i can't and have this message:

```
drupal module:install profile
[+] These configuration objects already exist in active configuration, installation is not possible
[-] profile.type.main
[-] system.action.profile_delete_action
[-] system.action.profile_publish_action
[-] system.action.profile_unpublish_action
```

Module stay disabled. The only way to enable it is to delete old configuration or use drush.

module:install should at least ask to override and lose previous configuration instead of doing nothing.

**Comment by darol100** [comment]
I do not think this issue is base on `[module:install]` instead of the module did not remove the configuration or did not override. 

You can run this command - \Drupal::configFactory()->getEditable('your.config)->delete(); and it will remove your configuration.

There is also a issue to support remove configuration at https://github.com/hechoendrupal/DrupalConsole/issues/1366.

Because all these reason, this issue is irrelevant so I'm closing this issue.
