### ISSUE TITLE
Console must not be hosted on drupal.org because MIT license is not allowed

### ISSUE THREAD

**Issue by klausi** [hechoendrupal/DrupalConsole#1671]
Please remove the code from drupal.org http://cgit.drupalcode.org/console/tree/LICENSE or change the license to GPLv2+.

**Comment by enzolutions** [comment]
@klausi I am not an expert in this matter, but I want to know how Drupal use Jquery since Drupal 6 and jquery use MIT License https://jquery.org/license/ in the same way symfony componens use MIT as you can see at http://symfony.com/doc/current/contributing/code/license.html 

Thanks in advance for your clarification

**Comment by klausi** [comment]
Those projects are granted exceptions when they are bundled with Drupal.

From https://www.drupal.org/node/1001544 :

"All files checked into the repository (code and assets) must be licensed under GNU/GPL version 2 and later."

**Comment by klausi** [comment]
OK, since Console must switch its license to GPL anyway I think we can close this. Once #1672 is implemented the license file on drupal.org will say that it is GPL.
