### ISSUE TITLE
Only Command classes loaded from themes

### ISSUE THREAD

**Issue by mdrummond** [hechoendrupal/DrupalConsole#1717]
Drupal Console Command classes can now be loaded in a theme. However, any supporting classes do not appear to load.

For example, a Generator class added in src/Generator is not picked up when the Command class has a use statement like so:

use Drupal\thememachinename\Generator\ClassNameForGenerator

and the Generator class has a namespace like so:

Drupal\thememachinename\Generator

It's always possible I'm setting this up wrong, but it seems like Console just isn't loading the custom Generator class. The error I'm getting is:

PHP Fatal error:  Class 'Drupal\thememachinename\Generator\ClassNameForGenerator' not found in pathtolocal/themes/thememachinename/src/Command/Generate/ClassNameForCommand.php on line 210

The error is specifically coming from drupal/src/Command/GeneratorCommand.php:31 in the stack trace.

The call stack shows this is coming from the createGenerator() method in the custom theme command. So I think the issue is that Console's Generator Command doesn't know what to do with the theme's generator class because there is no use statement for it within console. Maybe?

Although the more I experiment the more it feels like even the custom theme Command can't load the custom theme Generator.

You can find the example code in https://www.drupal.org/sandbox/mdrummond/2636658.

**Comment by darol100** [comment]
:+1:  I had the same discussing with @jmolivas  yesterday about something like this. Because I try to use a Drupal plugin  (custom image formatter) in my theme and did not work. You can find more discussion about that at [Its possible to load “Image Formatter” on a theme?](https://drupal.stackexchange.com/questions/186310/its-possible-to-load-image-formatter-on-a-theme)


However, It seem like the [Bootstrap project](https://drupal.org/project/bootstrap) is doing something to autoloading some of the classes and they are using Drupal plugins in their theme.


This feature is going to be very handy specially for contrib themes, otherwise we have to have a module as dependency so we can load our classes and add logic to it that on the theme layer we cant handle.

**Comment by jmolivas** [comment]
I like the idea of autoloading the commands using a better method the the implemented one. I will try to do by using composer. I will add another comment once I test this.

**Comment by fmann** [comment]
I think this is an issue in modules as well as themes that try to provide custom Generators.

I'm taking a stab at #1306. No problem adding a command in layout_plugin/src/Command, but I get the same class not found error from createGenerator() as described above. I've added the Generator to layout_plugin/src/Generator.

**Comment by darol100** [comment]
Here is an issue about this in Drupal.org - [Theme *.services.yml files aren't detected] (https://www.drupal.org/node/2002606). Which is kinda relate to this issue to this feature.

**Comment by darol100** [comment]
This have been fixed. Closing this issue.
