### ISSUE TITLE
[config:import:single] Doesn't work

### ISSUE THREAD

**Issue by OnkelTem** [hechoendrupal/DrupalConsole#2054]
I tried different combinations of params for `drupal config:import:single` command but in all cases it just hangs forever. I also passed `-v` but this didn't produce any output either.

**Comment by darol100** [comment]
I'm able to replicate this issues. @jmolivas it could be because of this https://github.com/hechoendrupal/DrupalConsole/commit/26f33662760aa12c310b6195ef96a5f578bd5364 ? I will try to revert this back and see if works.

I was able to input configuration name and after that does not anything.

**Comment by darol100** [comment]
I revert back https://github.com/hechoendrupal/DrupalConsole/commit/26f33662760aa12c310b6195ef96a5f578bd5364 and that was not the problem. And I did some testing with an older version of console 0.10.11 and I still have the same issue.

I will revert back this PR https://github.com/hechoendrupal/DrupalConsole/pull/1994 to see if that had something related too. However, I do not think this is related since I can replicate the same issue with 0.10.11

**Comment by darol100** [comment]
After some debugging this command still work. But not with the question. You need to add the parameters.  For instance.... `drupal config:import:single best.config module/bestmodule/config/best.config.yml`

What happens was that we introduce the interact for the command and input-file does not seem to be working.

**Comment by darol100** [comment]
I have create a PR that fixes this issue. #2070

**Comment by OnkelTem** [comment]
The file path should not be mandatory, by default the file should picked from `sync/` as this is done by `config:export:single` command.
