### ISSUE TITLE
Is 0.11 alpha quality ?

### ISSUE THREAD

**Issue by javian** [hechoendrupal/DrupalConsole#2121]
Is the 0.11 release stable or pre-alpha quality ? Its not very clear looking at the releases page =)
I would like to update the homebrew formula so I want to make sure before I push out the new version.

**Comment by darol100** [comment]
0.11 is a version that was released before Alpha, it was release to find unexpected issue between Drupal 8.0.x and Drupal 8.1.x. Currently in Drupal 8.1.x, they have updated some Symfony components which force the Drupal Console to update those components. So we did a release with those components updated because some people was asking for it; however, we can't just set Drupal Console to support Drupal 8.1.x, because Drupal 8.0.x still supported.

We will be dropping the support for Drupal 8.0.x in the alpha release, which should be after April 15. And we are going to be supporting Drupal 8.1.x.

For homebrew release, I will wait until we get the alpha release otherwise is going to break Drupal Console for anyone that is using Drupal 8.0.x.

**Comment by javian** [comment]
Thanks for the elaborate answer and I will keep an eye out on the development.

**Comment by darol100** [comment]
@javian , once we have an stable release of Drupal Console we should automate this step with Travis. In the future, whenever we are doing only minor release.

**Comment by javian** [comment]
Looking at the releases now it seems that 0.11.3 would be the recommended version for 8.0 and the new 1.0 alpha is for 8.1. As far as the homebrew formula goes I could add 0.11.3 to the regular release and a devel version which would be the drupcalconsole version for 8.1 so that they could be easily installed for now.
