### ISSUE TITLE
Bug in the Search bar ?

### ISSUE THREAD

**Issue by adraoo** [hechoendrupal/DrupalConsole#2158]
Hello,

When searching for 'mode' @hechoendrupal.gitbooks.io/drupal-console/content/en/
I was expecting to find the 'site:mode' (dev/prod) command, but it did not appear. I'm wondering if the parameter names are indexed.
![screen shot 2016-04-22 at 15 09 33](https://cloud.githubusercontent.com/assets/11652822/14742589/5a99f66e-089d-11e6-80c0-974fd6878d52.png)

Sincerely

**Comment by jmolivas** [comment]
@adraoo Search on gitbook does not look intuitive for me and a little buggy, I am attaching a short animated gif

![docs-search-filter](https://cloud.githubusercontent.com/assets/366275/14750788/68f2af02-087b-11e6-8f59-f061ec078414.gif)

With that said and since we don't have control over gitbook, the project we use for managing the documentation. This project is mostly to write docs for printing formats.

I decided to export drupal console command data as JSON, this is one example: 
https://gist.github.com/jmolivas/d6bd5e7b084bb5aa7cb1aabb2bbc9bd7

Having this data available our short-term goal is to build something similar to http://drushcommands.com/ using ReactJS.

**Comment by darol100** [comment]
Closing this issue since we can't kind control this git book search is not very intelligent. 

@adraoo , something to worth at looking at - http://drupalconsole.com/cheatsheet/
