### ISSUE TITLE
[generate:twig:extension] Generated services should not extend \Drupal\Core\Template\TwigExtension

### ISSUE THREAD

**Issue by SchnWalter** [hechoendrupal/DrupalConsole#2788]
Currently `drupal generate:twig:extension` generates a service that extends from `\Drupal\Core\Template\TwigExtension`. It should extend `\Twig_Extension` from twig library and add the dependency injection code on top of it, and maybe offer to add the `@renderer` service by default (a yes/no question)

If you start by removing the implemented methods that you don't need from the generated service, you will break functionality exposed by `\Drupal\Core\Template\TwigExtension` since your service will return functionality with the same and and [\Twig_Environment::initExtension](https://github.com/twigphp/Twig/blob/b75b3f75971682218e3d16412fbab2e4b67cb741/lib/Twig/Environment.php#L1432) overrides functionality with the same name that was declared previously in a different extension.

**Comment by jmolivas** [comment]
@SchnWalter This is what should be changed 

https://github.com/hechoendrupal/DrupalConsole/blob/master/templates/module/src/TwigExtension/twig-extension.php.twig#L12

from 
```
use Drupal\Core\Template\TwigExtension;
```
to 
```
use \TwigExtension;
```

And related to renderer, this is where is added by default instead of asking:

https://github.com/hechoendrupal/DrupalConsole/blob/master/src/Command/Generate/TwigExtensionCommand.php#L131

https://github.com/hechoendrupal/DrupalConsole/blob/master/templates/module/src/TwigExtension/twig-extension.php.twig#L43

**Comment by georch** [comment]
PR https://github.com/hechoendrupal/DrupalConsole/pull/2833 sent.
