### ISSUE TITLE
DrupalFinder dependency is not included in the composer.json

### ISSUE THREAD

**Issue by Julien-Marcou** [hechoendrupal/DrupalConsole#2936]
DrupalFinder is not included in the composer.json, but is required since the rc9, therefore I got a fatal error when using DrupalConsole if I don't install DrupalFinder myself.

> PHP Fatal error:  Class 'DrupalFinder\DrupalFinder' not found in /srv/www/drupal8/src/vendor/drupal/console/bin/drupal.php on line 29

**Comment by jmolivas** [comment]
@Julien-Marcou Yes is not included on this repo because is defined on the drupal-console-core repository https://github.com/hechoendrupal/drupal-console-core/blob/master/composer.json#L53

Try updating DrupalConsole following instructions at the repo readme file https://github.com/hechoendrupal/DrupalConsole#update-drupalconsole

**Comment by Julien-Marcou** [comment]
Running `composer update drupal/console --with-dependencies` did the trick, thanks !
