### ISSUE TITLE
Update from 0.11.3 to 1.0.0-rc10

### ISSUE THREAD

**Issue by cscmalaga** [hechoendrupal/DrupalConsole#2982]
Hi,

I'm using drupal-composer/drupal-project for our development that started with Drupal 8.0. This morning I updated composer.json to get latest Drupal version and Drupal Console was updated from 0.11.3 to 1.0.0-rc10.

Now Drupal Console takes more time to start up:
```
~/Projects/ctio-portal (develop)$ time ./ctioportal drupal --version
Drupal Console version 0.11.3

real	0m1.931s
user	0m0.240s
sys	0m0.040s`
```
```
~/Projects/ctio-portal (develop)$ time ./ctioportal drupal --version
Drupal Console version 1.0.0-rc10

real	0m3.070s
user	0m0.256s
sys	0m0.036s
```
And the other issue is that this command is creating a new directory into my project root: `console/log` Don't this must be created in _.console_ directory in my home?

Perhaps I forget some setting?

Regards.

**Comment by jmolivas** [comment]
@cmsmalaga  I did the same example with the following results
```
> time drupal --version
Drupal Console version 1.0.0-rc10
1.64 real         
1.37 user         
0.20 sys
```

Latest version is slower that previous since DrupalConsole now is reading and parsing YML files when registering services and compiling the container to register new services.

* https://github.com/hechoendrupal/DrupalConsole/tree/master/config/services/drupal-console
* https://github.com/hechoendrupal/DrupalConsole/tree/master/config/services/drupal-core

I am currently investigating how to cache the container and avoid reading those YAML files each time DrupalConsole is executed.

The `console` directory is created on the site since is logging errors related to the executed site.

I am not really happy with that feature and planning to rollback or at least to make it configurable by adding to the `config.yml` file something like this:
```
logging: 
  enable: true
  path: console/log #relative path to the site.
  path: ~/.console/SITE_NAME/log #fixed path.
```

**Comment by jmolivas** [comment]
I ran other test with the following results

![Alt text](https://monosnap.com/file/74leCAsNrkwvlC3kOIyjZN9lAoi1eL.png)

I will investigate how to improve the global launcher code

**Comment by cscmalaga** [comment]
I know that the new version do more things at startup, becase we have some code to authenticate users (a class implementing _AuthenticationProviderInterface_ interface), that now, with the rc10, it's runnning when drupal console is executed.

I'll do more test if I have time.

Thanks for your reply.

**Comment by jmolivas** [comment]
Closing this. Feel free to re-open it you think is needed.
