### ISSUE TITLE
Command "self-update", is not a valid command name

### ISSUE THREAD

**Issue by wturrell** [hechoendrupal/DrupalConsole#3001]
This is Drupal 8.2.4, the standard version (41 modules enabled) installed via Acquia Dev Desktop on MacOS 10.11.6 running PHP 7.0.4.  Drupal Console is version 1.0.0-rc10.

Most other console commands seem fine, except `drupal self-update`

Thanks,
William

**Comment by jmolivas** [comment]
@wturrell  Since RC releases the DC must be installer per project and therefore managed via composer (require and update)

The `self-update` command is now part of another project the https://github.com/hechoendrupal/drupal-console-launcher this is a global executable command plus some extra features.

**Comment by wturrell** [comment]
@jmolivas Thanks. I'd installed the launcher etc, but I'll just ignore the `self-update` command from now on and update DC the same way [drupal-project](https://github.com/drupal-composer/drupal-project) does.  

(Btw, thanks for your advice elsewhere on composer commands as it helped me fix a problem with symfony components.)

**Comment by ahoebeke** [comment]
Instead of throwing an error, could the launcher not print a message (or in addition to the error) specifying an answer such as yours? 
Things that are often so obvious for some are not documented, causing thousands of developers to waste valuable time because "error" will make you google-search for a solution, right?

**Comment by bheatonf1** [comment]
@ahoebeke Exactly!

**Comment by leymannx** [comment]
`drupal self-update` still in the docs. https://drupalconsole.com/docs/en/getting/launcher

**Comment by leymannx** [comment]
Ah got it! It needs to be run outside a project. https://github.com/hechoendrupal/drupal-console/issues/3198
