### ISSUE TITLE
list, self-update and --version shouldn't require running within a Drupal site

### ISSUE THREAD

**Issue by Jelle-S** [hechoendrupal/DrupalConsole#3019]
Following commands all throw the 

> DrupalConsole must be executed within a Drupal Site.

error:

```
$ drupal list
$ drupal self-update
$ drupal --version
```

While these should be able to run perfectly outside of a Drupal site.

EDIT running drupal/console 1.0.0-rc11

**Comment by jmolivas** [comment]
@Jelle-S Those commands `list` `self-update` and check the current installed version do not require a Drupal site to run.

If you install the Launcher aka global executable you will be able to see this:

![drupal-list-launcher](https://cloud.githubusercontent.com/assets/366275/21233564/6b134fd8-c2a4-11e6-82d5-be0b08be1cc9.png)

Instructions to download the Launcher 
https://github.com/hechoendrupal/DrupalConsole/#install-drupal-console-launcher

**Comment by jmolivas** [comment]
Closing this. Feel free to -re-open if think is required.

**Comment by daften** [comment]
I've traced this a bit further. The general launcher works indeed. What @Jelle-S is talking about is a project in which drupal/console is included, but not drupal itself. We got to that point, because we're creating a wrapper around drupal/console for robo.li. Now we can't write a decent test for this, because the output is always `DrupalConsole must be executed within a Drupal Site.`

I'm wondering why those 3 commands would need to be executed within a drupal site anyway. I'm guessing because since the major refactor drupal/console is meant to be used only in that context?
