### ISSUE TITLE
[multisite:new] Q: --site-uri and --uri params work differently

### ISSUE THREAD

**Issue by rpsu** [hechoendrupal/DrupalConsole#3029]
Executing `drupal multisite:new sitefolder.domain --uri="my.domain" ` "works", ie. does not throw errors nor notices, creates site-folder `sitefolder.domain` but fails to write sites.php -file. 

Would it make sense to use `--uri` -parameter, either replace `--site-uri` -parameter or simply as fallback if `--site-uri` is not set?
I'm not sure if the collision with drupal console's `--uri` -parameter actually prevents this. I'm happy to provide a patch if it makes sense and is technically possible.

**Comment by jmolivas** [comment]
@rpsu: Like the idea to use `--uri` to replace `--site-uri`, but not sure if this could be confusing since we used `--uri` to interact with multisite and will be using the same to provide a different behavior.

For now lets keep the same `--site-uri` but we need to:

* Force the `--site-uri` as `VALUE_REQUIRED`.

* Rename `--copy-install` as `--copy-default`

**Comment by jmolivas** [comment]
@rpsu I will take care of this since we are planing to tag a new release today.

**Comment by jmolivas** [comment]
Fixed with https://github.com/hechoendrupal/DrupalConsole/pull/3031
