### ISSUE TITLE
[router:debug] Add URI template name for entities

### ISSUE THREAD

**Issue by mpdonadio** [hechoendrupal/DrupalConsole#356]
To allow developers to know what the proper URL template to use for [Entity::urlInfo()](https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Core%21Entity%21Entity.php/function/Entity%3A%3AurlInfo/8), a column that shows this information would be handy for `drupal router:debug`

**Comment by jmolivas** [comment]
Can you please elaborate this @mpdonadio? in order we can take care of it.

**Comment by mpdonadio** [comment]
Let's say I have an node entity, and I want to get the URL object representing the route for the version history, I would do;

```
$url = $node->urlInfo('version-history');
```

Usually the URI templates are class annotations, sometimes they aren't.  When you are writing tests, or debugging code, and have entities and want to use routes, you need to know the link relationship from the template.

The feature request is to add a third column to `drupal route:debug` that shows this.  So

```
$ drupal route:debug | grep node | grep revision
entity.node.version_history     /node/{node}/revisions
```

becomes

```
$ drupal route:debug | grep node | grep revision
entity.node.version_history     /node/{node}/revisions     version-history
```

Routes w/o link relationships would just be empty.

**Comment by enzolutions** [comment]
Hi @mpdonadio 

Sorry for this late response.

I analyze your request and the problem is that function internaly call [Entity::toUrl](https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Core%21Entity%21Entity.php/function/Entity%3A%3AtoUrl/8) and that function only works under a real entity.

Because routing does'nt work with real entities is not possible to get that information.

My suggestion is create an issue in Drupal 8 Core to request a helper to enable us to get the URI Template from a Cannonical URL non depending if we are calling from a real entity.

Please let me know if that make sense from you.

**Comment by darol100** [comment]
Since, this is been tag as "work as expected" and it have been inactive, I'm going to close this issue. 

It seem like this is not possible base on the @enzolutions response in the above comment.
