### ISSUE TITLE
[standards] Coding standards for the console itself

### ISSUE THREAD

**Issue by alexdesignworks** [hechoendrupal/DrupalConsole#635]
I was wondering if Drupal's coding standards will/should be applied to Drupal Console codebase.

For example, curly braces in functions definitions start from the next line, which is a Symphony/PSR standard. In Drupal opening brace starts on the same line.

If Drupal standards are used, then a phpcs Drupal standard can be used to check the code of console itself during build.

**Comment by jmolivas** [comment]
@alexdesignworks The Drupal Console is not a Drupal module, this project is a Symfony Application code is [PSR1](http://www.php-fig.org/psr/psr-1/) and [PSR2](http://www.php-fig.org/psr/psr-2/).

But since one of the features of this project is to generate code, this generated code must be (Drupal Standard)[https://www.drupal.org/coding-standards] this is something we have been taking care.

If there is any cleanup required on the generated code feel free to report or send a PR fixing the Twig template files.

**Comment by heitoralthmann** [comment]
Cool topic! My PHPCS is complaining on the code generated through `generate:theme` and I was wondering if I should create an issue and fix this.

According to @jmolivas this must be the way to go, then.

Thank you!

**Comment by LOBsTerr** [comment]
@heitoralthmann Please create a separate ticket and provide more details
