### ISSUE TITLE
Cleanup install instructions and rename the 'console' executable to 'drupal'

### ISSUE THREAD

**Issue by webflo** [hechoendrupal/DrupalConsole#653]
# Problem/Motivation

The first install steps downloads ``console.phar`` and then later, we rename this phar file to ``drupal``. This leads to confusion because the user will end up with a different executable if the project is installed via composer (or a simple git clone).

# Proposed resolution

Rename ``bin/console`` and ``bin/console.php`` to drupal.

**Comment by LowellMontgomery** [comment]
Hi, @webflo. I agree, but I believe the proposed resolution is also potentially confusing.

## My Observations:
* Renaming `console.phar` to `drupal` is an optional installation step. Anywhere we document Drupal  Console commands and use `drupal` in the example, there *should* be a note explaining that we are assuming the user has installed globally and renamed the `console.phar` to `drupal`.
* (But... ) Renaming `console.phar` to `drupal` is potentially confusing. It seems ambiguous, just as if we called it `console`.
* Since things like `drupal self-update` might confuse (new users might rightly expect typing a command like that would update the Drupal installation). So, maybe it could be called `drucon` (or something) internally and at the command line. Then the global installation step would be to move to: `/usr/local/bin/drucon`.

## Proposed resolution

Rename `bin/console` and `bin/console.php` to `drucon` (or something else less potentially confusing than `drupal`.

**Comment by webflo** [comment]
Yes, naming things is hard :)

I think Symfony based applications just go with console, maybe we should to the same? ``symfony/console`` was added to core a few days ago. I am not sure if core is going to expose console as executable in the future.

**Comment by LowellMontgomery** [comment]
Hmm... yeah, I suspect renaming to either `console` or `drupal` could lead to confusion, especially if the scope is global.

**Comment by jmolivas** [comment]
Totally agree, naming things is hard, actually is so hard, we had this discussion in the past and talk about different names:
- console 
- drupalcli
- drucli
- drupli
- drupcli
- drupalconsole
- drupal

**Comment by LowellMontgomery** [comment]
Hi, Jesus...

I still like `drucon`...  (`drupalcon` would probably get too many irrelevant results in searches. ;-) )

`DrConsole` or `drupalconsole` are also at least unambiguous.

But we shouldn't really think of this as naming. It's only an *alias* used at the command line. The project is still "Drupal Console". The alias could just be a bit more obvious, IMHO. FWIW, if I list the options I think are suitable in descending order, it looks like:

* drucon (
* drconsole
* drupalconsole
* console

**Comment by pfrenssen** [comment]
Renaming it to Drupal is really strange IMO, any of the 4 suggestions above seem more suitable.

**Comment by bojanz** [comment]
Yeah, I find drupal much more odd than console (which is a bit too generic).

dcli? Too bad the "drush" name is taken :P

**Comment by pfrenssen** [comment]
I've grown quite fond of "console" by now ☺

**Comment by jmolivas** [comment]
After some talks about this we are going to rename the executable as `drupal` instead of `console` to avoid posible naming collision with symfony/console component on core.
