### ISSUE TITLE
[standard] Drupal coding standards errors

### ISSUE THREAD

**Issue by jmolivas** [hechoendrupal/DrupalConsole#667]
As shown on Travis build:
https://travis-ci.org/hechoendrupal/DrupalConsole/jobs/66209788

There are some fixes to apply at:
* templates/module/src/Authentication/Provider/authentication-provider.php.twig
* templates/module/src/Controller/controller.php.twig
* templates/module/src/Plugin/Rest/Resource/rest.php.twig

**Comment by darol100** [comment]
@jmolivas , If this issue is already fixed should we close the issue ? Or does needs more work ? or testing ?

**Comment by jmolivas** [comment]
Is fine with me to closed, but it won't be reflected until new release. thoughts @omero @enzolutions @darol100

**Comment by omero** [comment]
I think that we need the new release before close this issue because can cause duplicates :)

**Comment by jmolivas** [comment]
Should we tag as fixed or not ideas?

**Comment by omero** [comment]
Well rethinking this ... most of the people that detects this kind of problems can find the issue and see that exist the fix on dev branch, also we don't have a 1.x release yet , so from the developer perspective, and the good control of the project issues, maybe close the issue is the best option :smiley:

**Comment by jmolivas** [comment]
Thanks both @darol100 & @omero closing this
