### ISSUE TITLE
Abandoned dependency? -- herrera-io/phar-update

### ISSUE THREAD

**Issue by siwinski** [hechoendrupal/DrupalConsole#806]
It appears the dependency `"herrera-io/phar-update": "1.*"` is abandoned upstream per its' source GitHub owner?: https://github.com/kherge-abandoned/php-phar-update

Are there any plans to replace this dependency with a non-abandoned alternative?  I ask because I would like to eventually package this project downstream for Fedora/EPEL but I do not want to be responsible for packaging an abandoned dependency.

**Comment by jmolivas** [comment]
Thanks for notifying, we will start to looking for current maintained alternatives.

**Comment by james-nesbitt** [comment]
I notice that the platform.sh guys are using 2.x of the deprecated phar-update in their build: "herrera-io/phar-update": "^2.0",

(https://github.com/platformsh/platformsh-cli/blob/development/composer.json)

I did see an alternatice phar-update package that seems to be maintained (at least it's had activity since 2013) https://github.com/padraic/phar-updater but I they don't even mention the deprecated herrera package, so they may be completely incompatible.

**Comment by jmolivas** [comment]
@james-nesbitt: We should go ahead and try this one, I like the idea of using this and try the provided [Github Release Strategy](https://github.com/padraic/phar-updater#github-release-strategy)

**Comment by jmolivas** [comment]
@siwinski Issue fixed.

**Comment by jmolivas** [comment]
@james-nesbitt: Thanks for the recommendation we used the `padraic/phar-updater` library to remove the abandoned and no longer maintained `kherge-abandoned/php-phar-update`.

**Comment by siwinski** [comment]
THANKS everyone!

@jmolivas no help required *yet* ;)  I'm still packaging Drupal 8 itself.  I will reach out to you if I need help and to let you know the status of the Fedora/EPEL packaging.
